### ISSUE TITLE
Need up/add  bacon/bacon-qr-code to v3.0

### ISSUE THREAD

**Issue by TheForwardDev** [moonshine-software/two-factor#2]
MoonShine Version
**3.0.0-rc.1**

Laravel Version
**11.34.2**

Laravel Fortify Version
**1.25**

Can't install with composer, when installed fortify package, they use  bacon/bacon-qr-code:^3.0 and fixes gradient in 3.0.1

`
composer require moonshine/two-factor
`

`
 Problem 1
    - moonshine/two-factor[1.0.0, ..., 1.0.4, 2.0.0] require bacon/bacon-qr-code ^2.0 -> found bacon/bacon-qr-code[2.0.0, ..., 2.0.8] but the package is fixed to v3.0.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires moonshine/two-factor * -> satisfiable by moonshine/two-factor[1.0.0, ..., 1.0.4, 2.0.0].
`

To fix:
from
`
        "bacon/bacon-qr-code": "^2.0",
`
to
`
        "bacon/bacon-qr-code": "^3.0",
`

**Comment by lee-to** [comment]
Fixed
